### PR TITLE
Fixes a bug in DoAction

### LINKED ISSUE #134: `ActionGenerator` is having a stroke
Gets impossible action

### PR DESCRIPTION
**Pull request by jamadaha**
Before it was unable to remove multifacts from the state, which it can now

Adds a lot of tests of DoAction
Improves ActionGeneration test
Moves generation of applicable literals to before action generation
General refactor of ActionGeneration
-closes #134

### CODE REVIEW

File: Test/Walker/ActionGenerator.cpp [hunk 1]
```diff
@@ -5,6 +5,79 @@
...
+        REQUIRE(before.at(1) != after.at(1));
+        REQUIRE(before.at(0) == after.at(0));
+    }
+
+    SECTION("End") {
+        auto candidateObjects = GetCandidateObjectsPlaceholder(2, 2);
+        auto iteration = GetIterators(candidateObjects);
+        REQUIRE(2 == iteration.size());
+        for (int i = 0; i < 4; i++) {
+            printf("%u %u\n", (*iteration.at(0)), (*iteration.at(1)));
```
Comment (kris701) [inline Test/Walker/ActionGenerator.cpp:69]: I dont think you intended to print this?

File: src/Walker/ActionGenerator.hpp [hunk 2]
```diff
@@ -12,16 +12,39 @@
...
 public:
-    ActionGenerator(PDDLDomain *domain, PDDLProblem *problem) : domain(domain), problem(problem) {};
-    std::vector<PDDLActionInstance*> GenerateActions(const PDDLState *state);
+    ActionGenerator(const PDDLDomain *domain, const PDDLProblem *problem) : domain(domain), problem(problem) {};
+    /// @brief For a given state, generate all possible action instances
+    std::vector<PDDLActionInstance> GenerateActions(const PDDLState *state) const;
+    /// @brief For a given action, generate all possible action instances
+    std::vector<PDDLActionInstance> GenerateActions(const PDDLAction *action, const PDDLState *state) const;
+
+    /// @brief For the given \p action append all possible object permutations to candidate objects, only looks at unary literals
```
Comment (kris701) [inline src/Walker/ActionGenerator.hpp:21]: Im not sure if \p does something special in VSCode, but its just gone in visual studio
Does VSCode not accept normal xml documentation?

**Review by kris701 — CHANGES_REQUESTED** [review]

**Review by kris701 — APPROVED** [review]
